
project_id = "mdwifkqdnqdvmgowwssz"

[api]
port = 54321
schemas = ["public", "storage", "extensions"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.steam-start]
verify_jwt = false

[functions.steam-callback]
verify_jwt = false
